linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.1
  maligned:
    suggest-new: true
  goconst:
    min-len: 2
    min-occurrences: 2
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - hugeParam
      - rangeValCopy
      - singleCaseSwitch
      - ifElseChain

linters:
  enable:
    - megacheck
    - revive
    - govet
    - unconvert
    - megacheck
    - structcheck
    - gas
    - gocyclo
    - dupl
    - misspell
    - unparam
    - varcheck
    - deadcode
    - typecheck
    - ineffassign
    - varcheck
    - stylecheck
    - gochecknoinits
    - exportloopref
    - gocritic
    - nakedret
    - gosimple
    - prealloc
  fast: false
  disable-all: true

issues:
  exclude-rules:
    - text: "unexported-return"
      linters:
        - revive
    - path: _test\.go
      linters:
        - gosec
        - dupl
    - text: "at least one file in a package should have a package comment"
      linters:
        - stylecheck
  exclude-use-default: false
